name: Dev BeamFi app
on:
  workflow_dispatch:
  push:
    branches: [dev]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/setup-ui-dev.sh && npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTENTFLYDEV }}"
          projectId: contentflydev
          channelId: live
