name: Dev BeamFi app
on:
  workflow_dispatch:
  push:
    branches: [dev]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: ./scripts/setup-ui-dev.sh && pnpm install && pnpm run build
        env:
          NEXT_PUBLIC_WEB_CRYPTO_KEY: ${{ secrets.NEXT_PUBLIC_WEB_CRYPTO_KEY }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEAMDEV_A5006 }}"
          projectId: beamdev-a5006
          channelId: live
