name: Legacy BeamFi app
on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: ./scripts/setup-ui-prod.sh && pnpm install && pnpm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEAMLEGACY_37D81 }}"
          projectId: beamlegacy-37d81
          channelId: live
