name: Prod BeamFi app
on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: ./scripts/setup-ui-prod.sh && pnpm install && pnpm run build
        env:
          NEXT_PUBLIC_WEB_CRYPTO_KEY: ${{ secrets.NEXT_PUBLIC_WEB_CRYPTO_KEY }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEAMFIPROD }}"
          projectId: beamfiprod
          channelId: live
